const roles = {
	BATTER: "BATTER",
	ALL_ROUNDER: "ALL-ROUNDER",
	BOWLER: "BOWLER",
	WICKETKEEPER: "WICKETKEEPER",
	CAPTAIN: "CAPTAIN",
	VICE_CAPTAIN: "VICE_CAPTAIN"
};

export default Object.freeze(roles);
